### PR TITLE
Secure Boot configuration

### PR DESCRIPTION
**Pull request by crawfxrd**
Shoehorn in logic from Device Manager to show only the Secure Boot Config entry on the front page.

- [`SecureBootConfigDxe`](https://github.com/system76/edk2/tree/943773983d71fb61db6e00da61d285d08efa8696/SecurityPkg/VariableAuthenticated/SecureBootConfigDxe)

secure-boot-config

### CODE REVIEW

**Comment by crawfxrd** [comment]
Inside the menu item:

secure-boot-config

---

Custom mode allows management of keys in firmware.

custom-mode

custom-options

---

Problem: We don't handle HII Popup in our UI. We get the default edk2 gray-on-blue boxes.

popup

**Comment by crawfxrd** [comment]
Custom mode options all look the same:

PK Options

Enroll PK

"Enroll _ using file" opens the file explorer.

I don't have a drive attached to this QEMU instance to show what it would look like, so it's just a blank page.

**Comment by crawfxrd** [comment]
Bare minimum UI to ensure users don't get their OS into an unbootable state:

ui

**Comment by WatchMkr** [comment]
Move Secure Boot Configuration to the main page.

```
Boot Default
One Time Boot
Change Boot Order

Secure Boot Configuration

Firmware Configuration Information
```

**Comment by WatchMkr** [comment]
Secure Boot Configuration page

Secure Boot Status     $Status
Enable/Disable Secure Boot (depending on status)

Delete System76 and Microsoft Keys (Use your own key)

Restore System76 and Microsoft Keys and Restart

########

Enable Secure Boot page
An operating system that includes secure boot support is required. Disable secure boot if your operating system does not boot.

Enable Secure Boot and Restart
Cancel

########

Disable Secure Boot page
Disabling secure boot allows non-verified operating systems to boot and may disable some OS security features.

Disable Secure Boot and Restart
Cancel

########

Delete System76 and Microsoft Keys (Use your own key) page
System76 and Microsoft keys will be deleted. Enroll custom keys from your operating system. Check your OS documentation for details. To facilitate setup, secure boot is disabled until you manually activate it."

Delete System76 and Microsoft Keys and Restart
Cancel

**Comment by crawfxrd** [comment]
Keep the space between "Delete..." and "Restore..."?

secure-boot-options

**Comment by WatchMkr** [comment]
Let's remove the space between "Delete" and "Restore".

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
