### PR TITLE
TPM2 support

### PR DESCRIPTION
**Pull request by jackpot51**
Enables firmware attestation and Bitlocker

### CODE REVIEW

**Comment by jackpot51** [comment]
I was able to confirm bitlocker is working with this change, on the addw2. We may want to look into TPM init reliability. Some boots it isn't showing up.

**Comment by crawfxrd** [comment]
> We may want to look into TPM init reliability. Some boots it isn't showing up.

Any idea on how frequently this happens?

And is it just edk2's initialization? I've only seen coreboot fail to detect the TPM device on first boot after flashing.

**Comment by jackpot51** [comment]
Found another issue - bitlocker recovery key has to be entered if a firmware update wipes the NVRAM

**Comment by jackpot51** [comment]
Looks like any firmware updates cause this... and other vendors are affected

https://www.dell.com/support/article/en-us/sln153694/updating-the-bios-on-dell-systems-with-bitlocker-enabled?lang=en

**Pull request merged**
