### PR TITLE
Allow booting from file

### PR DESCRIPTION
**Pull request by crawfxrd**
Allow using File Explorer to select an EFI application to boot.

### CODE REVIEW

**Comment by jackpot51** [comment]
Can you disable the `***NEW FILE***` and `***NEW FOLDER***` items? They do not work as expected

**Comment by jackpot51** [comment]
Rebased this on latest system76 branch. I think that moving the device path to the help like what is done on the one time boot page would be good.

**Comment by jackpot51** [comment]
Also, we may want to add drive name next to volume label

**Comment by jackpot51** [comment]
```
DRIVE: VOLUME LABEL
...


Device Path : lakjsdfkljasdf
```

**Comment by crawfxrd** [comment]
Another issue is browser volumes with a lot of directories: they just run off the form.

**Comment by crawfxrd** [comment]
Scrolling elements handled with system76/firmware-setup#10.

**Comment by crawfxrd** [comment]
By extension, long lines like the ACPI UID exceed the width of the display, so the whole string cannot be viewed.

**Pull request closed without merging**
